spring.application.name=backend
server.port=${PORT:8080}
spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/workflow_db}
spring.mongodb.database=${MONGO_DB:workflow_db}
spring.devtools.restart.enabled=false
