spring.application.name=backend
server.port=${PORT:8080}
spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/workflow_db}
spring.mongodb.database=${MONGO_DB:workflow_db}
spring.devtools.restart.enabled=false
ai.service.base-url=${AI_SERVICE_BASE_URL:http://localhost:8001}
ai.service.generate-form-path=/api/v1/ai/generate-form
ai.service.generate-all-forms-path=/api/v1/ai/generate-all-forms
ai.service.generate-path=${AI_SERVICE_GENERATE_PATH:/api/v1/ai/generate-flow}
